name: streamlit
dependencies:
  - python=3.10
  - pip
  - pip:
    - pandas
    - python-dotenv
    - boto3
    - ipykernel
    - vaderSentiment
    - plotly==5.19.0
    - streamlit
    # - scikit-learn
    # - seaborn